### ISSUE TITLE
umi 4.x 中webpack 5 monaco-editor 0.44.0 的打包失败的问题

### ISSUE THREAD

**Issue by failgoddess** [DTStack/dt-monaco-editor-nls-webpack-plugin#2]
import MonacoWebpackPlugin from 'monaco-editor-esm-webpack-plugin';
const chainWebpack = (config: any, { webpack }: any) => {
  config.plugin('monaco-editor').use(MonacoWebpackPlugin, [
    {
      languages: ['mysql', 'pgsql', 'sql', 'xml', 'html', 'json', 'freemarker2', 'text'],
    },
  ]);
};

这样配置打包出现
fatal - Error: Parse config file failed: [/Users/vinc/Documents/github/TestHub/client/.umirc.ts]
    at Config.getUserConfig (/Users/vinc/Documents/github/TestHub/client/node_modules/@umijs/core/dist/config/config.js:161:17)
    at Config.getUserConfig (/Users/vinc/Documents/github/TestHub/client/node_modules/@umijs/core/dist/config/config.js:58:19)
    at Service.run (/Users/vinc/Documents/github/TestHub/client/node_modules/@umijs/core/dist/service/service.js:233:37)
    at Service.run2 (/Users/vinc/Documents/github/TestHub/client/node_modules/umi/dist/service/service.js:65:23)
    at /Users/vinc/Documents/github/TestHub/client/node_modules/umi/dist/cli/forkedDev.js:23:19
    at Object.<anonymous> (/Users/vinc/Documents/github/TestHub/client/node_modules/umi/dist/cli/forkedDev.js:36:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  [cause]: Error: Cannot find module 'webpack/lib/NormalModuleReplacementPlugin'
  Require stack:
  - /Users/vinc/Documents/github/TestHub/client/node_modules/monaco-editor-esm-webpack-plugin/src/core.js
  - /Users/vinc/Documents/github/TestHub/client/node_modules/monaco-editor-esm-webpack-plugin/index.js
  - /Users/vinc/Documents/github/TestHub/client/.umirc.ts
  - /Users/vinc/Documents/github/TestHub/client/node_modules/@umijs/core/dist/config/config.js
  - /Users/vinc/Documents/github/TestHub/client/node_modules/@umijs/core/dist/index.js
  - /Users/vinc/Documents/github/TestHub/client/node_modules/umi/dist/service/service.js
  - /Users/vinc/Documents/github/TestHub/client/node_modules/umi/dist/cli/forkedDev.js
  - /Users/vinc/Documents/github/TestHub/client/node_modules/umi/bin/forkedDev.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
      at mod._resolveFilename (/Users/vinc/Documents/github/TestHub/client/node_modules/umi/dist/service/requireHook.js:13:26)
      at Module._load (node:internal/modules/cjs/loader:922:27)
      at Module.require (node:internal/modules/cjs/loader:1143:19)
      at require (node:internal/modules/cjs/helpers:119:18)
      at Object.<anonymous> (/Users/vinc/Documents/github/TestHub/client/node_modules/monaco-editor-esm-webpack-plugin/src/core.js:2:46)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
      at Object.newLoader [as .js] (/Users/vinc/Documents/github/TestHub/client/node_modules/@umijs/utils/compiled/pirates/index.js:1:1684)
      at Module.load (node:internal/modules/cjs/loader:1119:32) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/vinc/Documents/github/TestHub/client/node_modules/monaco-editor-esm-webpack-plugin/src/core.js',
      '/Users/vinc/Documents/github/TestHub/client/node_modules/monaco-editor-esm-webpack-plugin/index.js',
      '/Users/vinc/Documents/github/TestHub/client/.umirc.ts',
      '/Users/vinc/Documents/github/TestHub/client/node_modules/@umijs/core/dist/config/config.js',
      '/Users/vinc/Documents/github/TestHub/client/node_modules/@umijs/core/dist/index.js',
      '/Users/vinc/Documents/github/TestHub/client/node_modules/umi/dist/service/service.js',
      '/Users/vinc/Documents/github/TestHub/client/node_modules/umi/dist/cli/forkedDev.js',
      '/Users/vinc/Documents/github/TestHub/client/node_modules/umi/bin/forkedDev.js'
    ]
  }
}

**Comment by liuxy0551** [comment]
这个包验证过的 monaco-editor 版本为 `0.30.1` 和 `0.31.1`，高一点的版本路径会有变化，建议对比 [vscode-loc](https://github.com/microsoft/vscode-loc/blob/release/1.63.3/i18n/vscode-language-pack-zh-hans/translations/main.i18n.json) 不同版本时 main.i18n.json 文件内 contents 内容的路径。

另外这个包针对我们的业务场景精简了 main.i18n.json 文件，因为 vscode-loc 的这个文件较大。


<img width="776" alt="image" src="https://github.com/DTStack/dt-monaco-editor-nls-webpack-plugin/assets/34759874/6c1d19ff-3dc1-43f3-b800-5be0234418ae">
